import type { Metadata } from "next";
import "./globals.css";
import ThemeToggle from "../components/theme-toggle";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta name="color-scheme" content="light dark" />
        <script
          dangerouslySetInnerHTML={{
            __html: `(() => { try { const pref = localStorage.getItem('theme'); const sys = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'; const mode = pref || sys; const root = document.documentElement; if (mode === 'dark') { root.classList.add('dark'); root.style.colorScheme = 'dark'; } else { root.classList.remove('dark'); root.style.colorScheme = 'light'; } } catch (_) {} })();`,
          }}
        />
      </head>
      <body className="font-exo2 antialiased">
        <ThemeToggle />
        {children}
      </body>
    </html>
  );
}
